### ISSUE TITLE
[bug] Fails at `read -r -N 1` on Mac OS

### ISSUE THREAD

**Issue by yashsk8** [simonmysun/ell#25]
Env:
device: Mac M2 Pro 
shell: zsh

Error:
`~/.ellrc.d/plugins/paginator/90_pre_output.sh: line 24: read: -N: invalid option`

location(s):
~/.ellrc.d/plugins/paginator/90_pre_output.sh: line 24
~/.ellrc.d/plugins/paginator/90_pre_output.sh: line 28
~/.ellrc.d/plugins/syntax_highlight/50_post_llm.sh: line  78

Resolution: replace `-N` with `-n`

**Comment by Artoria2e5** [comment]
Try: brew install bash.

**Comment by simonmysun** [comment]
Hi, 

Thank you for reporting. I have written the shebang of `#!/usr/bin/env bash` so it should have been executed with bash. I guess the problem is caused by low version of bash on Mac OS. I will try to figure out a workaround if there is any. Before there is a fix, you may consider upgrade your bash with homebrew or macports.

**Comment by simonmysun** [comment]
The `-N` option is introduced in Bash 4.1, I should write a notice when ell is executed with an earlier version

**Comment by yashsk8** [comment]
`bew install upgrade`  did it. Perfect, thanks!
